version: '3.7'

services:
  webapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: webapi
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_URLS=http://+:80
      - DB_SERVER=database
      - DB_PORT=5432
      - DB_DATABASE=postgres
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    depends_on:
      - database

  database:
    image: postgres:latest
    container_name: webapi-db
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
